run:
  timeout: 1m
  build-tags:
    - integration

linters:
  enable-all: true
  disable:
    - tenv

linters-settings:
  lll:
    line-length: 120
  depguard:
    rules:
      main:
        list-mode: lax
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
          - $gomod

      tests:
        list-mode: lax
        files:
          - $test
        allow:
          - $gostd
          - $gomod

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - err113
        - exhaustruct
