server:
#  address: "127.0.0.1:8443"
  https:
    enabled: true
    certFile: ./cert.pem
    keyFile: ./key.pem
authorization:
  - name: auth-name1
    key: MYSECRETKEY
urlCommands:
  - url: POST /cmd/echo
    authorizationName: auth-name1
    commandTemplate: |
      /bin/echo
      {{.url.message}}
    timeout: 30s
  - url: GET /cmd/date
    commandTemplate: |
      /usr/bin/date
      +%Y-%m-%d %H:%M:%S
    timeout: 30s
  - url: POST /cmd/echo-text
    commandTemplate: |
      /bin/echo
      -n
      {{.body.text}}
    timeout: 5s
  - url: POST /cmd/echo-json
    commandTemplate: |
      /bin/echo
      -n
      {{.body.json.message}}
    params:
      bodyAsJson: true
    timeout: 5s
  - url: GET /stream/time
    commandTemplate: |
      bash
      -c
      for i in {1..10}; do echo -n "$i "; date '+%H:%M:%S'; sleep 1; done
    outputType: stream
    timeout: 30s
  - url: GET /stream/time-with-timeout-5
    commandTemplate: |
      bash
      -c
      for i in {1..10}; do echo -n "$i "; date '+%H:%M:%S'; sleep 1; done
    outputType: stream
    timeout: 5s
  - url: GET /cmd/sleep
    commandTemplate: |
      /bin/sleep
      5
    outputType: none
    timeout: 10s
