### Test echo command, missing key
POST http://localhost:8080/cmd/echo?message=hello123

### Test echo command, invalid key
POST http://localhost:8080/cmd/echo?message=hello123
X-Api-Key: bad-key

### Test echo command
POST http://localhost:8080/cmd/echo?message=hello123
X-Api-Key: MYSECRETKEY

### Test date command
GET http://localhost:8080/cmd/date

### Test stream time
GET http://localhost:8080/stream/time

### Test stream time with timeout 5 seconds
GET http://localhost:8080/stream/time-with-timeout-5
