### Test echo command, missing key
POST http://localhost:8080/cmd/echo?param1=hello123

### Test echo command
POST http://localhost:8080/cmd/echo?param1=hello123
X-Api-Key: ABC111

### Test echo command, invalid key
POST http://localhost:8080/cmd/echo?param1=hello123
X-Api-Key: bad-key

### Test date command
GET http://localhost:8080/cmd/date
