// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dkarczmarski/webcmd/pkg/server/internal/handlers (interfaces: CommandExecutor)
//
// Generated by this command:
//
//	mockgen -typed -destination=internal/mocks/mock_server.go -package=mocks github.com/dkarczmarski/webcmd/pkg/server/internal/handlers CommandExecutor
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	config "github.com/dkarczmarski/webcmd/pkg/config"
	handlers "github.com/dkarczmarski/webcmd/pkg/server/internal/handlers"
	gomock "go.uber.org/mock/gomock"
)

// MockCommandExecutor is a mock of CommandExecutor interface.
type MockCommandExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockCommandExecutorMockRecorder
	isgomock struct{}
}

// MockCommandExecutorMockRecorder is the mock recorder for MockCommandExecutor.
type MockCommandExecutorMockRecorder struct {
	mock *MockCommandExecutor
}

// NewMockCommandExecutor creates a new mock instance.
func NewMockCommandExecutor(ctrl *gomock.Controller) *MockCommandExecutor {
	mock := &MockCommandExecutor{ctrl: ctrl}
	mock.recorder = &MockCommandExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommandExecutor) EXPECT() *MockCommandExecutorMockRecorder {
	return m.recorder
}

// RunCommand mocks base method.
func (m *MockCommandExecutor) RunCommand(ctx context.Context, cmd *config.CommandConfig, params map[string]any) handlers.CommandResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunCommand", ctx, cmd, params)
	ret0, _ := ret[0].(handlers.CommandResult)
	return ret0
}

// RunCommand indicates an expected call of RunCommand.
func (mr *MockCommandExecutorMockRecorder) RunCommand(ctx, cmd, params any) *MockCommandExecutorRunCommandCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunCommand", reflect.TypeOf((*MockCommandExecutor)(nil).RunCommand), ctx, cmd, params)
	return &MockCommandExecutorRunCommandCall{Call: call}
}

// MockCommandExecutorRunCommandCall wrap *gomock.Call
type MockCommandExecutorRunCommandCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCommandExecutorRunCommandCall) Return(arg0 handlers.CommandResult) *MockCommandExecutorRunCommandCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCommandExecutorRunCommandCall) Do(f func(context.Context, *config.CommandConfig, map[string]any) handlers.CommandResult) *MockCommandExecutorRunCommandCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCommandExecutorRunCommandCall) DoAndReturn(f func(context.Context, *config.CommandConfig, map[string]any) handlers.CommandResult) *MockCommandExecutorRunCommandCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
