server:
  address: ":8080"
authorization:
  - name: auth-name1
    key: ABC111
  - name: auth-name2
    key: ABC222
urlCommands:
  - url: POST /cmd/echo
    authorizationName: auth-name1,auth-name2
    commandTemplate: |
      /bin/echo
      {{.param1}}
      {{.param2}}
    timeout: 5
  - url: POST /cmd/sleep
    commandTemplate: |
      /usr/bin/sleep
      20
    timeout: 30