// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dkarczmarski/webcmd/pkg/cmdrunner (interfaces: Runner,Command)
//
// Generated by this command:
//
//	mockgen -typed -destination=./internal/mocks/mock_cmdrunner.go -package=mocks github.com/dkarczmarski/webcmd/pkg/cmdrunner Runner,Command
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	os "os"
	reflect "reflect"
	syscall "syscall"

	cmdrunner "github.com/dkarczmarski/webcmd/pkg/cmdrunner"
	gomock "go.uber.org/mock/gomock"
)

// MockRunner is a mock of Runner interface.
type MockRunner struct {
	ctrl     *gomock.Controller
	recorder *MockRunnerMockRecorder
	isgomock struct{}
}

// MockRunnerMockRecorder is the mock recorder for MockRunner.
type MockRunnerMockRecorder struct {
	mock *MockRunner
}

// NewMockRunner creates a new mock instance.
func NewMockRunner(ctrl *gomock.Controller) *MockRunner {
	mock := &MockRunner{ctrl: ctrl}
	mock.recorder = &MockRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRunner) EXPECT() *MockRunnerMockRecorder {
	return m.recorder
}

// Command mocks base method.
func (m *MockRunner) Command(ctx context.Context, name string, arg ...string) cmdrunner.Command {
	m.ctrl.T.Helper()
	varargs := []any{ctx, name}
	for _, a := range arg {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Command", varargs...)
	ret0, _ := ret[0].(cmdrunner.Command)
	return ret0
}

// Command indicates an expected call of Command.
func (mr *MockRunnerMockRecorder) Command(ctx, name any, arg ...any) *MockRunnerCommandCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, name}, arg...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Command", reflect.TypeOf((*MockRunner)(nil).Command), varargs...)
	return &MockRunnerCommandCall{Call: call}
}

// MockRunnerCommandCall wrap *gomock.Call
type MockRunnerCommandCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRunnerCommandCall) Return(arg0 cmdrunner.Command) *MockRunnerCommandCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRunnerCommandCall) Do(f func(context.Context, string, ...string) cmdrunner.Command) *MockRunnerCommandCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRunnerCommandCall) DoAndReturn(f func(context.Context, string, ...string) cmdrunner.Command) *MockRunnerCommandCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockCommand is a mock of Command interface.
type MockCommand struct {
	ctrl     *gomock.Controller
	recorder *MockCommandMockRecorder
	isgomock struct{}
}

// MockCommandMockRecorder is the mock recorder for MockCommand.
type MockCommandMockRecorder struct {
	mock *MockCommand
}

// NewMockCommand creates a new mock instance.
func NewMockCommand(ctrl *gomock.Controller) *MockCommand {
	mock := &MockCommand{ctrl: ctrl}
	mock.recorder = &MockCommandMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommand) EXPECT() *MockCommandMockRecorder {
	return m.recorder
}

// ProcessState mocks base method.
func (m *MockCommand) ProcessState() *os.ProcessState {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessState")
	ret0, _ := ret[0].(*os.ProcessState)
	return ret0
}

// ProcessState indicates an expected call of ProcessState.
func (mr *MockCommandMockRecorder) ProcessState() *MockCommandProcessStateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessState", reflect.TypeOf((*MockCommand)(nil).ProcessState))
	return &MockCommandProcessStateCall{Call: call}
}

// MockCommandProcessStateCall wrap *gomock.Call
type MockCommandProcessStateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCommandProcessStateCall) Return(arg0 *os.ProcessState) *MockCommandProcessStateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCommandProcessStateCall) Do(f func() *os.ProcessState) *MockCommandProcessStateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCommandProcessStateCall) DoAndReturn(f func() *os.ProcessState) *MockCommandProcessStateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetStderr mocks base method.
func (m *MockCommand) SetStderr(w io.Writer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStderr", w)
}

// SetStderr indicates an expected call of SetStderr.
func (mr *MockCommandMockRecorder) SetStderr(w any) *MockCommandSetStderrCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStderr", reflect.TypeOf((*MockCommand)(nil).SetStderr), w)
	return &MockCommandSetStderrCall{Call: call}
}

// MockCommandSetStderrCall wrap *gomock.Call
type MockCommandSetStderrCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCommandSetStderrCall) Return() *MockCommandSetStderrCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCommandSetStderrCall) Do(f func(io.Writer)) *MockCommandSetStderrCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCommandSetStderrCall) DoAndReturn(f func(io.Writer)) *MockCommandSetStderrCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetStdout mocks base method.
func (m *MockCommand) SetStdout(w io.Writer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStdout", w)
}

// SetStdout indicates an expected call of SetStdout.
func (mr *MockCommandMockRecorder) SetStdout(w any) *MockCommandSetStdoutCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStdout", reflect.TypeOf((*MockCommand)(nil).SetStdout), w)
	return &MockCommandSetStdoutCall{Call: call}
}

// MockCommandSetStdoutCall wrap *gomock.Call
type MockCommandSetStdoutCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCommandSetStdoutCall) Return() *MockCommandSetStdoutCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCommandSetStdoutCall) Do(f func(io.Writer)) *MockCommandSetStdoutCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCommandSetStdoutCall) DoAndReturn(f func(io.Writer)) *MockCommandSetStdoutCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetSysProcAttr mocks base method.
func (m *MockCommand) SetSysProcAttr(attr *syscall.SysProcAttr) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSysProcAttr", attr)
}

// SetSysProcAttr indicates an expected call of SetSysProcAttr.
func (mr *MockCommandMockRecorder) SetSysProcAttr(attr any) *MockCommandSetSysProcAttrCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSysProcAttr", reflect.TypeOf((*MockCommand)(nil).SetSysProcAttr), attr)
	return &MockCommandSetSysProcAttrCall{Call: call}
}

// MockCommandSetSysProcAttrCall wrap *gomock.Call
type MockCommandSetSysProcAttrCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCommandSetSysProcAttrCall) Return() *MockCommandSetSysProcAttrCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCommandSetSysProcAttrCall) Do(f func(*syscall.SysProcAttr)) *MockCommandSetSysProcAttrCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCommandSetSysProcAttrCall) DoAndReturn(f func(*syscall.SysProcAttr)) *MockCommandSetSysProcAttrCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Start mocks base method.
func (m *MockCommand) Start() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start")
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockCommandMockRecorder) Start() *MockCommandStartCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockCommand)(nil).Start))
	return &MockCommandStartCall{Call: call}
}

// MockCommandStartCall wrap *gomock.Call
type MockCommandStartCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCommandStartCall) Return(arg0 error) *MockCommandStartCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCommandStartCall) Do(f func() error) *MockCommandStartCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCommandStartCall) DoAndReturn(f func() error) *MockCommandStartCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Wait mocks base method.
func (m *MockCommand) Wait() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Wait")
	ret0, _ := ret[0].(error)
	return ret0
}

// Wait indicates an expected call of Wait.
func (mr *MockCommandMockRecorder) Wait() *MockCommandWaitCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wait", reflect.TypeOf((*MockCommand)(nil).Wait))
	return &MockCommandWaitCall{Call: call}
}

// MockCommandWaitCall wrap *gomock.Call
type MockCommandWaitCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCommandWaitCall) Return(arg0 error) *MockCommandWaitCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCommandWaitCall) Do(f func() error) *MockCommandWaitCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCommandWaitCall) DoAndReturn(f func() error) *MockCommandWaitCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
